import 'dayjs/locale/tr';
import type { FluentTemplate } from './type';

const tr_TR: FluentTemplate = {
  home: 'Ana Sayfa',
  categories: 'Kategoriler',
  collections: 'Koleksiyonlar',
  profile: 'Profil',

  'top-selling': 'Çok Satanlar',
  'see-all': 'Tümünü Gör',
  'latest-products': 'En Yeni Ürünler',
  'trending-products': 'Trend Ürünler',
  'sign-in': 'Giriş Yap',
  'sign-in-to-view-your-profile': 'Profilinizi ve siparişlerinizi görüntülemek için giriş yapın',
  'sign-in-to-continue-shopping': 'Alışverişe devam etmek için giriş yapın',
  'signing-in': 'Giriş yapılıyor...',
  'welcome': 'Hoş Geldiniz',
  'welcome-back': 'Tekrar Hoş Geldiniz',
  'friend': 'Arkadaş',
  'forgot-password': 'Şifrenizi mi unuttunuz?',
  'remember-me': 'Beni hatırla',
  login: 'Giriş Yap',
  or: 'Veya',
  'continue-with-google': 'Google ile devam et',
  email: 'E-posta',
  'enter-your-email': 'E-postanızı girin',
  password: 'Şifre',
  'enter-your-password': 'Şifrenizi girin',
  'dont-have-an-account': 'Hesabınız yok mu?',
  'invalid-credentials': 'Geçersiz kimlik bilgileri. Lütfen tekrar deneyin.',
  'no-collections-found': 'Koleksiyon bulunamadı',
  cart: 'Sepet',
  checkout: 'Ödeme',
  'go-home': 'Ana Sayfaya Dön',
  'you-dont-have-anything-in-your-cart':
    'Sepetinizde hiçbir şey yok.\nÜrünlerimize göz atmaya başlamak için aşağıdaki bağlantıyı kullanın.',
  'profile-information': 'Profil Bilgileri',
  'order-with-id': 'Sipariş # { $id }',
  orders: 'Siparişler',
  'shipping-addresses': 'Teslimat Adresleri',
  logout: 'Çıkış Yap',
  'profile-details': 'Profil Detayları',
  name: 'Ad Soyad',
  phone: 'Telefon',
  'edit-profile': 'Profili Düzenle',
  save: 'Kaydet',
  cancel: 'İptal',
  'first-name': 'Ad',
  'last-name': 'Soyad',
  'no-orders-found': 'Sipariş bulunamadı',
  'sign-in-to-view-orders': 'Siparişlerinizi görmek için lütfen giriş yapın',
  view: 'Görüntüle',
  'remaining-items': '{ $count } tane daha',
  'no-categories-found': 'Kategori bulunamadı',
  variant: 'Varyant',
  'add-a-promo-code': 'Promosyon Kodu Ekle',
  'enter-promo-code': 'Promosyon kodunu girin',
  'applied-promotions': 'Uygulanan Promosyonlar',
  'invalid-promo-code': 'Geçersiz promosyon kodu',
  'failed-to-apply-promotion': 'Promosyon kodu uygulanamadı',
  'failed-to-remove-promotion': 'Promosyon kodu kaldırılamadı',
  apply: 'Uygula',
  summary: 'Özet',
  discount: 'İndirim',
  subtotal: 'Ara Toplam',
  shipping: 'Kargo',
  taxes: 'Vergiler',
  total: 'Toplam',
  'use-same-address-for-billing': 'Fatura için aynı adresi kullan',
  'shipping-address': 'Teslimat Adresi',
  'billing-address': 'Fatura Adresi',
  address: 'Adres',
  company: 'Şirket',
  optional: 'İsteğe Bağlı',
  'postal-code': 'Posta Kodu',
  city: 'Şehir',
  'province-or-state': 'İl/Eyalet',
  country: 'Ülke',
  'select-a-country': 'Ülke seçin',
  delivery: 'Teslimat',
  payment: 'Ödeme',
  review: 'İnceleme',
  'continue-to-delivery': 'Teslimata Devam Et',
  'continue-to-payment': 'Ödemeye Devam Et',
  'review-order': 'Siparişi İncele',
  'pay-using-provider': '{ $provider } ile öde',
  'place-order': 'Siparişi Tamamla',
  continue: 'Devam Et',
  'please-select-a-payment-method': 'Lütfen bir ödeme yöntemi seçin',
  'no-cart-found': 'Sepet bulunamadı',
  'payment-provider-not-supported': 'Ödeme sağlayıcısı desteklenmiyor',
  'failed-to-complete-order': 'Sipariş tamamlanamadı',
  error: 'Hata',
  'an-error-occurred': 'Bir hata oluştu',
  'no-cart-id': 'Sepet ID yok',
  'failed-to-update-shipping-method': 'Kargo yöntemi güncellenemedi',
  'loading-shipping-options': 'Kargo seçenekleri yükleniyor',
  'select-shipping-method': 'Kargo Yöntemi Seçin',
  calculating: 'Hesaplanıyor',
  'no-region-id': 'Bölge ID yok',
  'stripe-payment-coming-soon': 'Stripe ödeme arayüzü yakında gelecek!',
  'no-additional-actions-required-for-manual-payment':
    'Manuel ödeme için ek işlem gerekmiyor.',
  'payment-provider-is-in-development':
    'Ödeme sağlayıcısı { $provider } geliştirme aşamasında.',
  'loading-payment-options': 'Ödeme seçenekleri yükleniyor',
  'select-payment-method': 'Ödeme Yöntemi Seçin',
  qty: 'Adet',
  'shipping-method': 'Kargo Yöntemi',
  'payment-method': 'Ödeme Yöntemi',
  'no-shipping-method-selected': 'Kargo yöntemi seçilmedi',
  'no-payment-method-selected': 'Ödeme yöntemi seçilmedi',
  canceled: 'İptal Edildi',
  'not-fulfilled': 'Yerine Getirilmedi',
  'partially-fulfilled': 'Kısmen Yerine Getirildi',
  fulfilled: 'Yerine Getirildi',
  'partially-shipped': 'Kısmen Gönderildi',
  shipped: 'Gönderildi',
  'partially-delivered': 'Kısmen Teslim Edildi',
  delivered: 'Teslim Edildi',
  'count-items': '{ $count } ürün',
  'order-details': 'Sipariş Detayları',
  'order-not-found': 'Sipariş bulunamadı',
  'placed-on': '{ $datetime } tarihinde sipariş verildi',
  status: 'Durum',
  'order-items': 'Sipariş Ürünleri',
  contact: 'İletişim',
  method: 'Yöntem',
  'order-summary': 'Sipariş Özeti',
  'continue-shopping': 'Alışverişe Devam Et',
  addresses: 'Adresler',
  'please-sign-in-to-view-your-address':
    'Adreslerinizi görmek için lütfen giriş yapın',
  'no-addresses-found': 'Adres bulunamadı',
  'add-new-address': 'Yeni Adres Ekle',
  'add-address': 'Adres Ekle',
  'edit-address': 'Adresi Düzenle',
  'save-changes': 'Değişiklikleri Kaydet',
  'country-code': 'Ülke Kodu',
  'product-information': 'Ürün Bilgileri',
  material: 'Malzeme',
  'country-of-origin': 'Menşei',
  type: 'Tip',
  weight: 'Ağırlık',
  dimensions: 'Boyutlar',
  'days-return': '{ $count } gün iade',
  'fast-delivery': 'Hızlı Teslimat',
  'add-to-cart': 'Sepete Ekle',
  'out-of-stock': 'Stokta Yok',
  'view-cart': 'Sepeti Görüntüle',
  settings: 'Ayarlar',
  language: 'Dil',
  'select-language': 'Dil seçin',
  'language-is-required': 'Dil zorunludur',
  'first-name-is-required': 'Ad zorunludur',
  'last-name-is-required': 'Soyad zorunludur',
  'address-is-required': 'Adres zorunludur',
  'postal-code-is-required': 'Posta kodu zorunludur',
  'city-is-required': 'Şehir zorunludur',
  'country-is-required': 'Ülke zorunludur',
  'phone-is-required': 'Telefon zorunludur',
  'please-enter-a-valid-email': 'Lütfen geçerli bir e-posta girin',
  'invalid-email-address': 'Geçersiz e-posta adresi',
  'password-must-be-at-least-n-characters':
    'Şifre en az { $n } karakter olmalıdır',
  register: 'Kayıt Ol',
  'register-to-join-us': 'Bize katılmak için kayıt olun',
  'create-an-account-to-start-shopping': 'Alışverişe başlamak için hesap oluşturun',
  'enter-your-first-name': 'Adınızı girin',
  'enter-your-last-name': 'Soyadınızı girin',
  'create-account': 'Hesap Oluştur',
  'create-password': 'Şifre Oluştur',
  'confirm-password': 'Şifreyi Onayla',
  're-enter-your-password': 'Şifrenizi tekrar girin',
  'i-agree-to': 'Kabul ediyorum',
  'terms-and-condition': 'Şartlar ve koşullar',
  'passwords-must-match': 'Şifreler eşleşmelidir',
  'must-agree-to-terms': 'Şartları kabul etmelisiniz',
  'have-an-account': 'Zaten hesabınız var mı?',
  'creating-account': 'Hesap oluşturuluyor',
  'already-have-an-account': 'Zaten hesabınız var mı? Giriş Yapın',
  'registration-failed': 'Kayıt başarısız oldu. Lütfen tekrar deneyin.',

  // Favorites
  'my-favorites': 'Favorilerim',
  'products-count': '{ $count } Ürün',
  'no-favorites-yet': 'Henüz Favori Yok',
  'add-products-to-favorites': 'Favorilere Ürün Ekleyin',

  // Home
  'search-here': 'Buradan Arayın',
  balance: 'Bakiye',
  all: 'Tümü',
  popular: 'Popüler',

  // Info Pages - Categories
  corporate: 'Kurumsal',
  'campaigns-menu': 'Kampanya',
  seller: 'Satıcı',
  help: 'Yardım',

  // Info Pages - Corporate
  'about-us': 'Biz Kimiz',
  career: 'Kariyer',
  sustainability: 'Sürdürülebilirlik',
  'contact-us': 'İletişim',
  security: 'Bangoo\'da Güvenlik',

  // Info Pages - Campaigns
  campaigns: 'Kampanyalar',
  'elite-membership': 'Elit Üyelik',

  // Info Pages - Seller
  'sell-on-bangoo': 'Bangoo\'da Satış Yap',
  'basic-concepts': 'Temel Kavramlar',

  // Info Pages - Help
  faq: 'Sıkça Sorulan Sorular',
  'live-support': 'Canlı Yardım / Asistan',
  'how-to-return': 'Nasıl İade Edebilirim',
  'transaction-guide': 'İşlem Rehberi',

  // Checkout Steps
  'address-step': 'Adres',
  'delivery-step': 'Teslimat',
  'payment-step': 'Ödeme',
  'review-step': 'Önizleme',
  'province-is-required': 'İl zorunludur',
  'province': 'İl',
  'select-province': 'İl Seçin',
};

// Export as Fluent format - keys are already in correct format
export default Object.keys(tr_TR)
  .map(key => {
    // Use key as-is since they're already in kebab-case or correct format
    return `${key} = ${(tr_TR as any)[key]}`;
  })
  .join('\n');
